const { readFileSync, writeFileSync } = require('fs');
const { execSync } = require('child_process');
const path = require('path');

try {
  // Read base version
  const pkgPath = path.join(__dirname, '..', 'package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const baseVersion = pkg.version || '1.0.0';

  // Get current git hash
  let gitHash = 'unknown';
  try {
    gitHash = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
  } catch (e) {
    // Fallback if git is not initialized or fails
  }

  const version = `${baseVersion}-${gitHash}`;

  // Write to client/src/version.ts
  const outputPath = path.join(__dirname, '..', 'client', 'src', 'version.ts');
  const content = `// Generated by scripts/update-version.js\nexport const releaseVersion = "${version}";\n`;
  writeFileSync(outputPath, content, 'utf8');
  console.log(`Updated client/src/version.ts to version ${version}`);
} catch (error) {
  console.error('Failed to update version:', error);
  process.exit(1);
}
