const { readFileSync, writeFileSync } = require('fs');
const { execSync } = require('child_process');
const path = require('path');

function incrementVersion(version) {
	const parts = (version || '0.0').split('.');
	parts[parts.length - 1] = String(Number(parts[parts.length - 1]) + 1);
	return parts.join('.');
}

try {
	// Read base version from root package.json
  const pkgPath = path.join(__dirname, '..', 'package.json');
	const pkgContent = readFileSync(pkgPath, 'utf8');
	const pkg = JSON.parse(pkgContent);
	const oldVersion = pkg.version || '0.1';
	
	// Increment version
	const newVersion = incrementVersion(oldVersion);
	pkg.version = newVersion;
	
	// Write updated package.json back with formatting preserved
	writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
	console.log(`Incremented package.json version from ${ oldVersion } to ${ newVersion }`);

  // Get current git hash
  let gitHash = 'unknown';
  try {
    gitHash = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
  } catch (e) {
    // Fallback if git is not initialized or fails
  }
	
	const clientVersion = `${ newVersion }-${ gitHash }`;

  // Write to client/src/version.ts
  const outputPath = path.join(__dirname, '..', 'client', 'src', 'version.ts');
	const content = `// Generated by scripts/update-version.js\nexport const releaseVersion = "${ clientVersion }";\n`;
  writeFileSync(outputPath, content, 'utf8');
	console.log(`Updated client/src/version.ts to version ${ clientVersion }`);
} catch (error) {
  console.error('Failed to update version:', error);
  process.exit(1);
}

